apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJaM1Z6WTJocGJpMW5iM2RoZVRwbmFIQmZTM0ZQVlhkbFYwTmpSVU5ZVFdJeWRYTnhOR3BCYjBSc1ZGWnhWazl5TTB3MlJscGEiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson